### ISSUE TITLE
Handle players who avoid the nova

### ISSUE THREAD

**Issue by amazingalek** [misternebula/quantum-space-buddies#41]

**Comment by Raicuparta** [comment]
I think this will kinda fix itself? When a player avoids the nova, the game triggers a death of type `DeathType.TimeLoop`, which is one of the whitelisted death types (no respawn), and so it will just bring you to the main menu. You can then press "resume expedition" again, and you'll just reconnect on the same loop (as long as #71 is implemented). But maybe we can make it reset the loop as usual instead of going to the main menu?

Also, if #70 is implemented, the loops will act as separate universes, so players who avoid the loop together can see each other, but won't be able to see people on the next loop (and vice-versa).
